# config example
# 
# WaitAddress: wait ip:port available
#
# Directory: application work dic
# Exe:application name
# Environment:system environment  ["PYTHONPATH=/lib/python","CUDA=/lib/cuda"]
# FaildSecond:when server run faild,restart second time
# Args: server params
# UpdateFileName: when damon detecte zip file,automatic update
#
# [[Servers]]
# Directory = "/public/node"
# Exe = "node"
# Environment = ""
#
# [[Servers]]
# Directory = "/public/server"
# Exe = "server"
# Environment = ""

WaitAddress = []

[[Servers]]
Directory = ""
Exe = ""
Environment = []
FaildSecond = 5
Args = []
UpdateFileName = ""
