# config example
# 
# WaitAddress: wait ip:port available
#
# Directory: application work dic
# Exe:application name
# Environment:system environment  ["PYTHONPATH=/lib/python","CUDA=/lib/cuda"]
# FaildSecond:when server run faild,restart second time
# Args: server params
# UpdateFileName: when damon detecte zip file,automatic update
#
# [[Servers]]
# Directory = "/public/node"
# Exe = "node"
# Environment = ""
#
# [[Servers]]
# Directory = "/public/server"
# Exe = "server"
# Environment = ""

WaitAddress = ["10.8.0.60:3363"]

[[Servers]]
Directory = "/home/server"
Exe = "server"
Environment = ["PYTHONPATH=/lib/python","CUDA=/lib/cuda"]
FaildSecond = 5
Args = ["arg1=1","arg2=2"]
UpdateFileName = "update.zip"
